//
//  DetailsSceneModels.swift
//  AGLGoogleAPIProject
//
//  Created by Ильдар Аглиуллов on 06.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DetailsScene {
    // MARK: Use cases
    
    struct DisplayedSection: Equatable {
        enum SectionType: Equatable {
            case details
        }
        
        let type: SectionType
        
        struct DisplayedCell: Equatable {
            enum CellType: Equatable {
                case description(imageURL: URL?, webUrl: String?)
            }
            
            let type: CellType
        }
        
        let cells: [DisplayedCell]
    }
    
    enum Details {
        struct Request {
            let isNext: Bool
            let isPrev: Bool
        }
        struct Response {
            let detailsModel: ImagesResult?
        }
        struct ViewModel {
            let displayedSection: [DisplayedSection]
        }
    }
}
