//
//  DetailsSceneInteractor.swift
//  AGLGoogleAPIProject
//
//  Created by Ильдар Аглиуллов on 06.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsSceneBusinessLogic {
    func fetchImages(request: DetailsScene.Details.Request)
}

protocol DetailsSceneDataStore {
    var googleModel: GoogleSearchModel? { get set }
    var selectedIndex: Int? { get set }
}

final class DetailsSceneInteractor: DetailsSceneDataStore {
    
    var presenter: DetailsScenePresentationLogic?
    var worker: DetailsSceneWorker?
    
    var googleModel: GoogleSearchModel?
    var selectedIndex: Int?
}

extension DetailsSceneInteractor: DetailsSceneBusinessLogic {
    
    func fetchImages(request: DetailsScene.Details.Request) {
        guard var index = selectedIndex, let googleModel = googleModel else { return }
        
        if request.isNext, index < googleModel.imagesResults.endIndex - 1 {
            index += 1
        } else if request.isPrev, index >= 1 {
            index -= 1
        }
        
        self.selectedIndex = index
        let model = googleModel.imagesResults[safeIndex: index]
        let response = DetailsScene.Details.Response(detailsModel: model)
        presenter?.presentDetailsImage(response: response)
    }
}
