//
//  DetailsSceneRouter.swift
//  AGLGoogleAPIProject
//
//  Created by Ильдар Аглиуллов on 06.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsSceneRoutingLogic {
    func openWebView(urlString: String?)
}

protocol DetailsSceneDataPassing {
    var dataStore: DetailsSceneDataStore? { get }
}

final class DetailsSceneRouter: DetailsSceneRoutingLogic, DetailsSceneDataPassing {
    
    weak var viewController: DetailsSceneViewController?
    var dataStore: DetailsSceneDataStore?
    
    // MARK: Routing
    
    func openWebView(urlString: String?) {
        guard let viewController = self.viewController else { return }
        let detailsVC = WebViewContoller()
        detailsVC.urlString = urlString
        self.navigateToDetailsVC(source: viewController, destination: detailsVC)
    }
    
    // MARK: Navigation
    
    func navigateToDetailsVC(source: DetailsSceneViewController, destination: WebViewContoller) {
        source.present(destination, animated: true, completion: nil)
    }
}
