//
//  DetailsScenePresenter.swift
//  AGLGoogleAPIProject
//
//  Created by Ильдар Аглиуллов on 06.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsScenePresentationLogic {
    func presentDetailsImage(response: DetailsScene.Details.Response)
}

final class DetailsScenePresenter {
    
    weak var viewController: DetailsSceneDisplayLogic?
    
    private func getSection(with data: ImagesResult?) -> [DetailsScene.DisplayedSection] {
        guard let data = data else { return [] }
        let cell = DetailsScene.DisplayedSection.DisplayedCell(type: .description(imageURL: URL(string: data.thumbnail), webUrl: data.link))
        let section = DetailsScene.DisplayedSection(type: .details, cells: [cell])
        return [section]
    }
}

extension DetailsScenePresenter: DetailsScenePresentationLogic {
    
    func presentDetailsImage(response: DetailsScene.Details.Response) {
        let section = getSection(with: response.detailsModel)
        let viewModel = DetailsScene.Details.ViewModel(displayedSection: section)
        viewController?.displayDetailsFetchedImages(viewModel: viewModel)
    }
}
