//
//  MainSceneWorker.swift
//  AGLGoogleAPIProject
//
//  Created by Ильдар Аглиуллов on 06.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

final class MainSceneWorker {
    
    private var networkDataFetcher: NetworkDataFetcher
    
    init(networkDataFetcher: NetworkDataFetcher = NetworkDataFetcher()) {
        self.networkDataFetcher = networkDataFetcher
    }
    
    func fetchGoogleImages(url: String, completion: @escaping (GoogleSearchModel?) -> Void) {
        networkDataFetcher.getDataURLFromJson(urlString: url, response: completion)
    }
}
