//
//  MainSceneModels.swift
//  AGLGoogleAPIProject
//
//  Created by Ильдар Аглиуллов on 06.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainScene {
    // MARK: Use cases
    
    struct DisplayedSection: Equatable {
        enum SectionType: Equatable {
            case main
        }
        
        let type: SectionType
        
        struct DisplayedCell: Equatable {
            enum CellType: Equatable {
                case main(titleText: String?, subtitleText: String?, imageURL: URL?)
                case empty
            }
            
            let type: CellType
        }
        
        let cells: [DisplayedCell]
    }
    
    enum Main {
        struct Request {
            let inputText: String
        }
        struct Response {
            let model: GoogleSearchModel?
        }
        struct ViewModel {
            let displayedSection: [DisplayedSection]
        }
    }
    
    enum OpenDetails {
        struct Request {
            let index: Int
        }
        struct Response {

        }
        struct ViewModel {

        }
    }
}
