//
//  MainSceneRouter.swift
//  AGLGoogleAPIProject
//
//  Created by Ильдар Аглиуллов on 06.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainSceneRoutingLogic {
    func routeToDetails()
}

protocol MainSceneDataPassing {
    var dataStore: MainSceneDataStore? { get }
}

final class MainSceneRouter: MainSceneRoutingLogic, MainSceneDataPassing {
    
    weak var viewController: MainSceneViewController?
    var dataStore: MainSceneDataStore?
    
    // MARK: Routing
    
    func routeToDetails() {
        guard let viewController = self.viewController else { return }
        
        let detailsVC = DetailsSceneViewController()
        guard let sourceDataStore = self.dataStore, var destinationDataSource = detailsVC.router?.dataStore else { return }
        
        self.passDataToDetailsVC(source: sourceDataStore, destination: &destinationDataSource)
        self.navigateToDetailsVC(source: viewController, destination: detailsVC)
    }
    
    // MARK: Navigation
    
    func navigateToDetailsVC(source: MainSceneViewController, destination: DetailsSceneViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToDetailsVC(source: MainSceneDataStore, destination: inout DetailsSceneDataStore) {
        destination.selectedIndex = source.selectedIndex
        destination.googleModel = source.googleModel
    }
}
