//
//  MainSceneInteractor.swift
//  AGLGoogleAPIProject
//
//  Created by Ильдар Аглиуллов on 06.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainSceneBusinessLogic {
    func fetchImages(request: MainScene.Main.Request)
    func openDetailsViewController(request: MainScene.OpenDetails.Request)
}

protocol MainSceneDataStore {
    var googleModel: GoogleSearchModel? { get set }
    var selectedIndex: Int? { get set }
}

final class MainSceneInteractor: MainSceneDataStore {
    
    var presenter: MainScenePresentationLogic?
    var worker: MainSceneWorker = MainSceneWorker()
    
    var googleModel: GoogleSearchModel?
    var selectedIndex: Int?
}

// MARK: - MainSceneBusinessLogic

extension MainSceneInteractor: MainSceneBusinessLogic {
    
    func fetchImages(request: MainScene.Main.Request) {
        if request.inputText == "" {
            let response = MainScene.Main.Response(model: nil)
            presenter?.presentFetchedData(response: response)
        } else {
            let api_key = "c2f9cdb5696becaef645bd752548b03af1171d7549bdc039671a950a2ba07e5f"
            let url = "https://serpapi.com/search.json?engine=google&tbm=isch&api_key=\(api_key)&q=\(request.inputText)"
            
            DispatchQueue.main.async {
                self.worker.fetchGoogleImages(url: url, completion: { [weak self] data in
                    if let self = self, let data = data {
                        self.googleModel = data
                        
                        let response = MainScene.Main.Response(model: data)
                        self.presenter?.presentFetchedData(response: response)
                    } else {
                        let response = MainScene.Main.Response(model: nil)
                        self?.presenter?.presentFetchedData(response: response)
                    }
                })
            }
        }
    }
    
    func openDetailsViewController(request: MainScene.OpenDetails.Request) {
        self.selectedIndex = request.index
        let response = MainScene.OpenDetails.Response()
        presenter?.presentDetailsVC(response: response)
    }
}
