//
//  MainScenePresenter.swift
//  AGLGoogleAPIProject
//
//  Created by Ильдар Аглиуллов on 06.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainScenePresentationLogic {
    func presentFetchedData(response: MainScene.Main.Response)
    func presentDetailsVC(response: MainScene.OpenDetails.Response)
}

final class MainScenePresenter {

    weak var viewController: MainSceneDisplayLogic?
    
    private func getSection(model: GoogleSearchModel?) -> [MainScene.DisplayedSection] {
        var sections: [MainScene.DisplayedSection] = []
        var cells: [MainScene.DisplayedSection.DisplayedCell] = []
        
        if let model = model {
            model.imagesResults.forEach { result in
                let cell = MainScene.DisplayedSection.DisplayedCell(type: .main(titleText: result.title, subtitleText: result.source, imageURL: URL(string: result.thumbnail)))
                cells.append(cell)
            }
        } else {
            let cell = MainScene.DisplayedSection.DisplayedCell(type: .empty)
            cells.append(cell)
        }
        let section = MainScene.DisplayedSection(type: .main, cells: cells)
        sections.append(section)
        return sections
    }
    
}

extension MainScenePresenter: MainScenePresentationLogic {
    
    func presentFetchedData(response: MainScene.Main.Response) {
        let sections = getSection(model: response.model)
        
        let viewModel = MainScene.Main.ViewModel(displayedSection: sections)
        viewController?.displayFetchedImages(viewModel: viewModel)
    }
    
    func presentDetailsVC(response: MainScene.OpenDetails.Response) {
        let viewModel = MainScene.OpenDetails.ViewModel()
        viewController?.displayDetailsVC(viewModel: viewModel)
    }
}
